In [4]:
import pandas as pd
df = pd.read_csv('student_performance_dataset.csv')

In [6]:
df

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade
0,1,Male,4.0,98.0,6.5,Bachelors,Yes,Yes,No,76.9,100.0,A
1,2,Female,6.3,100.0,5.7,High School,Yes,Yes,Yes,75.5,100.0,A
2,3,Male,4.9,85.3,7.9,Bachelors,Yes,No,Yes,88.5,97.3,A
3,4,Male,2.6,77.5,8.0,NaN,Yes,Yes,No,85.1,83.8,B
4,5,Male,2.2,89.6,4.6,Bachelors,Yes,No,Yes,61.8,68.3,D
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Male,2.8,75.4,8.2,Masters,Yes,Yes,No,60.5,70.7,C
996,997,Male,6.7,88.4,7.1,NaN,No,Yes,No,82.2,99.5,A
997,998,Female,2.6,84.5,8.0,High School,Yes,Yes,Yes,65.2,79.2,C
998,999,Female,4.6,85.3,8.1,High School,No,No,Yes,52.2,82.2,B
999,1000,Male,3.9,77.4,6.1,Masters,Yes,No,No,45.4,70.4,C

In [ ]:
from scipy import stats

notas_sin_trabajo = df[df['part_time_job'] == 'No']['final_exam_score']
notas_con_trabajo = df[df['part_time_job'] == 'Yes']['final_exam_score']
stat_sin, p_norm_sin = stats.shapiro(notas_sin_trabajo)
stat_con, p_norm_con = stats.shapiro(notas_con_trabajo)

print(f'Normalidad (Sin trabajo) - p-value: {p_norm_sin}')
print(f'Normalidad (Con trabajo) - p-value: {p_norm_con}')

stat_lev, p_lev = stats.levene(notas_sin_trabajo, notas_con_trabajo)
print(f'Homogeneidad de Varianzas - p-value: {p_lev}')

Normalidad (Sin trabajo) - p-value: 6.538077779618806e-10
Normalidad (Con trabajo) - p-value: 0.0008025497667783155
Homogeneidad de Varianzas - p-value: 0.06552834131438612

In [14]:
media = df.groupby('part_time_job')['final_exam_score'].agg(
    total_personas='count',
    media_nota='mean'
).reset_index()

media

  part_time_job  total_personas  media_nota
0            No             684   84.582310
1           Yes             316   81.294937

In [24]:
notas_con_trabajo = df[df['part_time_job'] == 'Yes']['final_exam_score']
notas_sin_trabajo = df[df['part_time_job'] == 'No']['final_exam_score']
t_stat, p_value = stats.ttest_ind(notas_sin_trabajo, notas_con_trabajo)

print(f'T de student para la prueba:{t_stat:.2f}')
print(f'p-valor: {p_value:.2e}')

T de student para la prueba:4.72
p-valor: 2.66e-06

In [25]:
import numpy as np
d_cohen = t_stat * np.sqrt(1/len(notas_sin_trabajo) + 1/len(notas_con_trabajo))

print(f"la d de Cohen es: {d_cohen:.2f}")

la d de Cohen es: 0.32